apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytestapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mytestapi
  template:
    metadata:
      labels:
        app: mytestapi
    spec:
      containers:
        - name: mytestapi
          image: stevepro/mytestapi:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3080 
