apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapidockerkind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapidockerkind
  template:
    metadata:
      labels:
        app: webapidockerkind
    spec:
      containers:
        - name: webapidockerkind
          image: webapidockerkind:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3080 
